In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Arrays

In [3]:
X = np.array([1,2,3])

In [6]:
type(X), X.shape, X[0], X[1], X[2]

(numpy.ndarray, (3,), np.int64(1), np.int64(2), np.int64(3))

In [7]:
print(type(X), X.shape, X[0], X[1], X[2])

<class 'numpy.ndarray'> (3,) 1 2 3


In [8]:
y = np.array([[1,3,4], [2,5,4]])

In [10]:
y.shape

(2, 3)

In [12]:
print(y[1][1])

5


In [13]:
z= np.zeros((2,2))

In [14]:
z

array([[0., 0.],
       [0., 0.]])

In [16]:
o = np.ones((2,3))

In [17]:
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
i = np.eye(3) #Identity matrix

In [21]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
c = np.full((2,3), 4) # for defining matrix with constant

In [25]:
c

array([[4, 4, 4],
       [4, 4, 4]])

In [34]:
rand = np.random.random((3,3,3))

In [35]:
rand

array([[[0.89153284, 0.30919928, 0.71940555],
        [0.50836925, 0.24659553, 0.85947502],
        [0.1681448 , 0.03504619, 0.91777874]],

       [[0.89135684, 0.60855159, 0.71898094],
        [0.01329528, 0.08480946, 0.29882674],
        [0.03181844, 0.70689246, 0.69426881]],

       [[0.46990495, 0.46234661, 0.03009059],
        [0.21611321, 0.68107769, 0.90411498],
        [0.29820441, 0.25892618, 0.5869089 ]]])

In [36]:
b = rand[:][0][0]

In [37]:
b

array([0.89153284, 0.30919928, 0.71940555])

In [49]:
b= rand[:2][0][-1]

In [50]:
b

array([0.1681448 , 0.03504619, 0.91777874])

In [51]:
c = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [52]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
c[:2,1:3]

array([[2, 3],
       [5, 6]])

In [57]:
c[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [58]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [59]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
row_r1 = ar[1,:] #second row with rank 1

In [71]:
row_r2 = ar[1:2, :] #second row with rank 2

In [72]:
row_r3 = ar[[1],:] #second row with rank 2

In [73]:
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [74]:
col_c1 = ar[:, 1]
col_c2 = ar[:, 1:2]
col_c3 = ar[:, [1]]

In [75]:
print(col_c1, col_c1.shape)
print(col_c2, col_c2.shape)
print(col_c3, col_c3.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[[ 2]
 [ 6]
 [10]] (3, 1)


## Creating array using indices

In [81]:
b = np.array([0, 1, 2]) # created to define indices
b

array([0, 1, 2])

In [82]:
print(ar[np.arange(3), b]) #printing specified indices

[11 16 21]


In [83]:
ar[np.arange(3), b] += 10 #changing values of those indices
ar

array([[21,  2,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 10, 31, 12]])

In [86]:
bool_idx = (ar>5) #boolian matrix
bool_idx

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
br = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [89]:
print(ar+br)

[[22  4  6  8]
 [10 32 14 16]
 [18 20 42 24]]


In [90]:
print(ar-br)

[[20  0  0  0]
 [ 0 20  0  0]
 [ 0  0 20  0]]


In [91]:
print(np.add(ar, br))

[[22  4  6  8]
 [10 32 14 16]
 [18 20 42 24]]
