In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [2]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation="softmax")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [7]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8785 - loss: 0.4303
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9651 - loss: 0.1177
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9776 - loss: 0.0765
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9832 - loss: 0.0566
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9869 - loss: 0.0429
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9903 - loss: 0.0321
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9923 - loss: 0.0255
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9945 - loss: 0.0187
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9956 - loss: 0.0154
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9959 - loss: 0.0145


In [8]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('\nTest accuracy:', test_acc)

313/313 - 1s - 3ms/step - accuracy: 0.9771 - loss: 0.0777

Test accuracy: 0.9771000146865845


In [9]:
y_pred = model.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [10]:
y_pred

array([[9.67969524e-11, 9.20297527e-09, 5.03880742e-08, ...,
        9.99993622e-01, 1.74718651e-09, 1.32824480e-08],
       [4.37501251e-11, 1.58902694e-05, 9.99983847e-01, ...,
        1.07851276e-16, 1.18831935e-07, 5.74967329e-18],
       [3.32331296e-09, 9.99922693e-01, 6.79481218e-06, ...,
        5.33651728e-05, 1.26587411e-05, 7.01648795e-10],
       ...,
       [1.22406497e-18, 4.29965005e-12, 5.47324732e-20, ...,
        1.35812456e-07, 5.07225234e-11, 1.29145905e-09],
       [2.70382139e-09, 4.56226766e-12, 3.79400774e-16, ...,
        2.01919904e-12, 7.74056116e-06, 7.38936466e-15],
       [5.27592761e-11, 1.81155698e-11, 9.64437948e-13, ...,
        4.10616744e-16, 9.41402251e-12, 4.15177197e-13]], dtype=float32)

In [11]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [12]:
import numpy as np
top2_idx = np.argsort(y_pred[0])[-2:][::-1]      # indices of top 2 probs
top2_prob = y_pred[0][top2_idx]                  # their probabilities

for digit, prob in zip(top2_idx, top2_prob):
    print(f"Digit {digit} → Probability {prob:.4f}")

Digit 7 → Probability 1.0000
Digit 3 → Probability 0.0000


In [13]:
top2_idx_all = np.argsort(y_pred, axis=1)[:, -2:][:, ::-1]   # top 2 indices
top2_prob_all = np.take_along_axis(y_pred, top2_idx_all, axis=1)  # top 2 probs

In [14]:
top2_idx_all

array([[7, 3],
       [2, 1],
       [1, 7],
       ...,
       [4, 7],
       [5, 8],
       [6, 4]])

In [16]:
import pandas as pd
result_df = pd.DataFrame({
    'y_test': y_test,
    'top1_digit': top2_idx_all[:, 0],
    'top1_prob': top2_prob_all[:, 0],
    'top2_digit': top2_idx_all[:, 1],
    'top2_prob': top2_prob_all[:, 1]
})

In [17]:
result_df

,y_test,top1_digit,top1_prob,top2_digit,top2_prob
0,7,7,0.999994,3,6.360642e-06
1,2,2,0.999984,1,1.589027e-05
2,1,1,0.999923,7,5.336517e-05
3,0,0,1.000000,2,9.946961e-09
4,4,4,0.999995,9,4.255582e-06
...,...,...,...,...,...
9995,2,2,0.999998,1,2.006374e-06
9996,3,3,0.999998,5,2.123868e-06
9997,4,4,1.000000,7,1.358125e-07
9998,5,5,0.999992,8,7.740561e-06


In [19]:
result_df.to_csv("result.csv")

## Lets apply CNN

In [21]:
X_train.shape

(60000, 28, 28)

In [22]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model2 = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D(pool_size=(2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [27]:
model2.fit(X_train, y_train, epochs=2, validation_data=(X_test, y_test))

Epoch 1/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 62s 33ms/step - accuracy: 0.9909 - loss: 0.0305 - val_accuracy: 0.9905 - val_loss: 0.0282
Epoch 2/2
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 78s 31ms/step - accuracy: 0.9941 - loss: 0.0184 - val_accuracy: 0.9908 - val_loss: 0.0303


In [28]:
test_loss2, test_acc2 = model2.evaluate(X_test, y_test, verbose=2)
print('\nTest accuracy:', test_acc2)

313/313 - 3s - 10ms/step - accuracy: 0.9908 - loss: 0.0303

Test accuracy: 0.9908000230789185


In [29]:
y_pred2 = model2.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step


In [30]:
import numpy as np
top2_idx2 = np.argsort(y_pred2[0])[-2:][::-1]      # indices of top 2 probs
top2_prob2 = y_pred2[0][top2_idx]                  # their probabilities

for digit, prob in zip(top2_idx2, top2_prob2):
    print(f"Digit {digit} → Probability {prob:.4f}")

Digit 7 → Probability 0.9999
Digit 3 → Probability 0.0001


In [31]:
top2_idx_all2 = np.argsort(y_pred2, axis=1)[:, -2:][:, ::-1]   # top 2 indices
top2_prob_all2 = np.take_along_axis(y_pred2, top2_idx_all2, axis=1)  # top 2 probs

In [32]:
import pandas as pd
result_df2 = pd.DataFrame({
    'y_test': y_test,
    'top1_digit': top2_idx_all2[:, 0],
    'top1_prob': top2_prob_all2[:, 0],
    'top2_digit': top2_idx_all2[:, 1],
    'top2_prob': top2_prob_all2[:, 1]
})

In [34]:
result_df2.to_csv("result_CNN.csv")